### ISSUE TITLE
`typst init @preview/ttt-exams my-exam` failed to find package @preview/ttt-exams

### ISSUE THREAD

**Issue by julyfun** [jomaway/typst-teacher-templates#3]
## Env

* MacOS 14.5
* typst 0.11.0

## Command in terminal

In an empty folder:

```
typst init @preview/ttt-exams my-exam
```

## Error

```
error: failed to find package @preview/ttt-exams
        ⏰ 1.160s       📅 24-05-27 14:40:09
```

**Comment by jomaway** [comment]
Sorry for the inconvenience. There is a typo in the readme. Try without the s at the end. 
`typst init @preview/ttt-exam`

**Comment by jomaway** [comment]
fixed in readme
